-- AlterTable
ALTER TABLE "ApiKey" ADD COLUMN     "requestsPerMinute" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "windowRequests" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "windowStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

