"use client";

/**
 * Glass surfaces: panels that refract what is behind them at their edges.
 *
 * The effect is a backdrop-filter pointed at an SVG filter. That filter runs
 * feDisplacementMap three times over the backdrop, once per colour channel at
 * slightly different strengths, and screens the results back together. Doing it
 * per channel is what produces the faint colour fringing along an edge, which
 * is the thing that reads as glass rather than as blur: real glass disperses,
 * and a single displacement pass looks like a smear.
 *
 * The displacement maps are generated by scripts/make_glass_maps.py rather than
 * pasted in as base64. Two of them, because the filter stretches its map over
 * whatever it is applied to, so a square map on a wide header would smear the
 * band along the top and bottom.
 *
 * The rim is separate from the refraction and does more of the work: a bright
 * inset hairline where light catches the edge, a wider soft inset under it, and
 * a few dark inset layers for thickness.
 *
 * Firefox does not support a url() filter in backdrop-filter. The fallback is
 * the default here and the refraction is the upgrade, so a browser without it
 * gets a plain frosted panel rather than a transparent rectangle.
 */

import type { ReactNode } from "react";

/**
 * The filters themselves, mounted once per page.
 *
 * An SVG filter is referenced by id from CSS, so it has to be in the document
 * even though it draws nothing. Hidden from assistive technology and taken out
 * of the layout rather than display:none, which stops a filter resolving in
 * some browsers.
 */
export function GlassFilters() {
  return (
    <svg aria-hidden className="pointer-events-none absolute h-0 w-0 opacity-0">
      <defs>
        {(
          [
            ["glass-bar", "/glass-bar.png"],
            ["glass-card", "/glass-card.png"],
          ] as const
        ).map(([id, href]) => (
          <filter
            key={id}
            id={id}
            colorInterpolationFilters="sRGB"
            x="0%"
            y="0%"
            width="100%"
            height="100%"
          >
            <feImage
              x="0"
              y="0"
              width="100%"
              height="100%"
              preserveAspectRatio="none"
              result="map"
              href={href}
            />

            {/* One pass per channel. The scales differ by a few units, which is
                the whole of the dispersion: red bends least, blue most. */}
            <feDisplacementMap
              in="SourceGraphic"
              in2="map"
              result="dispRed"
              scale="-16"
              xChannelSelector="R"
              yChannelSelector="G"
            />
            <feColorMatrix
              in="dispRed"
              type="matrix"
              values="1 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0"
              result="red"
            />
            <feDisplacementMap
              in="SourceGraphic"
              in2="map"
              result="dispGreen"
              scale="-20"
              xChannelSelector="R"
              yChannelSelector="G"
            />
            <feColorMatrix
              in="dispGreen"
              type="matrix"
              values="0 0 0 0 0  0 1 0 0 0  0 0 0 0 0  0 0 0 1 0"
              result="green"
            />
            <feDisplacementMap
              in="SourceGraphic"
              in2="map"
              result="dispBlue"
              scale="-24"
              xChannelSelector="R"
              yChannelSelector="G"
            />
            <feColorMatrix
              in="dispBlue"
              type="matrix"
              values="0 0 0 0 0  0 0 0 0 0  0 0 1 0 0  0 0 0 1 0"
              result="blue"
            />

            <feBlend in="red" in2="green" mode="screen" result="rg" />
            <feBlend in="rg" in2="blue" mode="screen" result="output" />
            {/* Softens the seams the three passes leave behind. */}
            <feGaussianBlur in="output" stdDeviation="1.4" />
          </filter>
        ))}
      </defs>
    </svg>
  );
}

export type GlassVariant = "bar" | "card";

/**
 * A pane of it.
 *
 * `as` because these wrap a header in one place and a section in another, and
 * a div inside a landmark that should have been the landmark is a worse outcome
 * than a prop.
 */
export function Glass({
  children,
  className = "",
  variant = "card",
  as: Tag = "div",
}: {
  children: ReactNode;
  className?: string;
  variant?: GlassVariant;
  as?: "div" | "header" | "section" | "figure";
}) {
  return (
    <Tag className={`glass glass--${variant} ${className}`}>{children}</Tag>
  );
}
